<?php $page = $this->pages->getPage() ?>
<span title="Pages">
   <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABSUlEQVQ4T6WSsUrEQBCG/9lLjisEQRLt7h20tEov6Cv4AL6AILm9O0GwV3tBFC1sfICAonC13TWHZXLWFrvZkY2sxJC9U9xm2Jl/v/l3GMI/D22keo/Bm02OAU3no+BqGZ/igTophuFhUxin6oWYLvJxcLkIQuupkvkolE2RzTPwAcZzMQ4ffRAvIB7os2LYOYgH6galOSqOe9M2iBcQSb0rDG+5R20ube0LIIJRXKp9Iuq3dWEgISCr15ihmcu7CsDMb0bg9X3YnSyb+nddcnfN6EkFsElr0Q3U5WxnFpBkIG0UBonT2mh1PwBxqjJntQ60eRiekaDZQkDdQdORu7cC7ECKTnAaQW/PZZhFUiW+6L5hBDIwdqovGFNeA51bIXD/6yECK0y06t2DOsi3rdUeRKk+F+Dc15mBHgt6msvgoXUT/2C5VfoJrfrPjKj3lzcAAAAASUVORK5CYII="/>
   <?php if ($page) { ?>
   #<?=$page->getID()?> [<?=$page->getType()?>]
   <?php } else { ?>
   - not found -
   <?php } ?>
</span>